version: '3.7'
services:
  postgres:
    image: 'postgres:15.2-bullseye'
    container_name: 'yak_postgres'
    ports:
      - 5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=yakapi
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: ../Dockerfile
    container_name: 'yak_api'
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/yakapi
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis

  redis:
    image: 'redis:7.0.9-bullseye'
    container_name: 'yak_redis'
    ports:
      - 6379
    volumes:
      - redis:/data
volumes:
  pgdata:
  redis:
