version: "3.7"
services:
  postgres:
    image: "postgres:15.2-bullseye"
    container_name: "yak_postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: always
  redis:
    image: "redis:7.09-bullseye"
    container_name: "yak_redis"
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
