-- Add migration script here
CREATE TABLE IF NOT EXISTS YAK (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    AGE real NOT NULL,
    AGE_LAST_SHAVED real
);
alter table YAK alter column AGE_LAST_SHAVED set default 0;

INSERT INTO YAK (NAME, AGE, AGE_LAST_SHAVED) VALUES ('Betty', 10, 0);
INSERT INTO YAK (NAME, AGE, AGE_LAST_SHAVED) VALUES ('Betsy', 10, 0);
INSERT INTO YAK (NAME, AGE, AGE_LAST_SHAVED) VALUES ('Tommy', 10, 0);
INSERT INTO YAK (NAME, AGE, AGE_LAST_SHAVED) VALUES ('YakYak-binks', 10, 0);
INSERT INTO YAK (NAME, AGE, AGE_LAST_SHAVED) VALUES ('SOmething', 10, 0);
INSERT INTO YAK (NAME, AGE, AGE_LAST_SHAVED) VALUES ('SomethingElse', 10, 0);

