name: Build and test yak

on:
  pull_request:
    paths:
      - "yak/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  run_clippy:
    name: Run clippy
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cd yak && cargo clippy
  build_and_test:
    name: Run tests
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cd yak && cargo build
      - run: cd yak && cargo test --verbose
